version: '3'
services:
  web:
    image: amselim/get-started:flask_excel2
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
volumes:
  webVol: